const heros = [
    {
        id: 0,
        gender: 'male',
        hero: 'Spider-Man',
        nombre: 'Peter Parker',
        poder: 'sentido animal aracnido',
        villano: 'Duende Verde',
    },
    {
        id: 1,
        gender: 'male',
        hero: 'Profesor X',
        nombre: 'Charles Xavier',
        poder: 'telepátia natural',
        villano: 'Magneto',
    }, {
        id: 2,
        gender: 'male',
        hero: 'Capitán América',
        nombre: 'Steve Rogers',
        poder: 'super fuerza',
        villano: 'Red Skull',
    },
    {
        id: 3,
        gender: 'male',
        hero: 'Wolverine',
        nombre: 'James Logan',
        poder: 'mutante instinto animal',
        villano: 'Magneto',
    },
    {
        id: 4,
        gender: 'female',
        hero: 'Black Widow',
        nombre: 'Natasha Romanoff',
        poder: 'espía soviética natural',
        villano: 'Taskmaster',
    },
]